feign:
  hystrix:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
spring:
  application:
    name: Test-User

server:
  port: 0

user:
  name: Chris-He
